// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol KeysGlobalProtocol {
    var foursquareClientID: String { get }
    var foursquareClientSecret: String { get }
}

public protocol KeysEnvironmentProtocol {
}
